name: Install Qt
description: Install Qt on your Github Actions workflows with just one simple action
author: jurplel
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
  version:
    description: Version of Qt to install
    default: "5.15.2"
  host:
    description: Host platform
  target:
    description: Target platform for build
    default: desktop
  arch:
    description: Architecture for Windows/Android
  install-deps:
    description: Whether or not to install Qt dependencies on Linux
    default: true
  modules:
    description: Additional Qt modules to install
  archives:
    description: Specify which Qt archive to install
  cache:
    description: Whether or not to cache Qt automatically
    default: false
  cache-key-prefix:
    description: Cache key prefix for automatic cache
    default: install-qt-action
  setup-python:
    description: Whether or not to automatically run setup-python to find a valid python version.
    default: true
  tools:
    description: >
      Qt tools to download
      --
      specify comma-separated argument lists which are themselves separated by spaces:
      <tool_name>,<tool_version>,<tool_arch>
  set-env:
    default: true
    description: Whether or not to set environment variables after running aqtinstall
  tools-only:
    description: Whether or not to actually install Qt or just the tools from the tools argument
    default: false
  aqtversion:
    description: Version of aqtinstall to use in case of issues
    default: ==2.1.*
  py7zrversion:
    description: Version of py7zr to use in case of issues
    default: ==0.19.*
  extra:
    description: Any extra arguments to append to the back
runs:
  using: "composite"
  steps:
  - name: Setup Python 
    if: ${{ inputs.setup-python  == 'true' }}
    uses: actions/setup-python@v4
    with:
      python-version: '3.6.x - 3.11.x'

  - name: Setup and run aqtinstall
    uses: vicr123/install-qt-action/action@win-aarch64-test
    with:
      dir: ${{ inputs.dir }}
      version: ${{ inputs.version }}
      host: ${{ inputs.host }}
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      install-deps: ${{ inputs.install-deps }}
      modules: ${{ inputs.modules }}
      archives: ${{ inputs.archives }}
      cache: ${{ inputs.cache }}
      cache-key-prefix: ${{ inputs.cache-key-prefix }}
      tools: ${{ inputs.tools }}
      set-env: ${{ inputs.set-env }}
      tools-only: ${{ inputs.tools-only }}
      aqtversion: ${{ inputs.aqtversion }}
      py7zrversion: ${{ inputs.py7zrversion }}
      extra: ${{ inputs.extra }}